<a href="https://colab.research.google.com/github/saisahasraD/ML_LAB_2026-27/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

wine = load_wine()
X = wine.data
y = wine.tarASget

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.3, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("--- Model Evaluation (k=5) ---")
print(f"Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(
y_test, y_pred, target_names=wine.target_names
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

new_wine = np.array([[13.2, 1.78, 2.14, 11.2, 100, 2.65,
2.76, 0.26, 1.28, 4.38, 1.05, 3.4, 1050]])

new_wine_scaled = scaler.transform(new_wine)
prediction = knn.predict(new_wine_scaled)
predicted_class = wine.target_names[prediction[0]]

print("\n--- New Prediction ---")
print(f"Predicted wine class: {predicted_class}")


--- Model Evaluation (k=5) ---
Accuracy: 0.9630

Classification Report:
              precision    recall  f1-score   support

     class_0       0.95      1.00      0.97        19
     class_1       1.00      0.90      0.95        21
     class_2       0.93      1.00      0.97        14

    accuracy                           0.96        54
   macro avg       0.96      0.97      0.96        54
weighted avg       0.97      0.96      0.96        54


Confusion Matrix:
[[19  0  0]
 [ 1 19  1]
 [ 0  0 14]]

--- New Prediction ---
Predicted wine class: class_0


In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

penguins = sns.load_dataset('penguins')
penguins = penguins.dropna()
X = penguins[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]
y = penguins['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("--- Model Evaluation (k=5) ---")
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

new_penguin = pd.DataFrame([[39.1, 18.7, 181.0, 3750.0]], columns=X.columns)
new_penguin_scaled = scaler.transform(new_penguin)
prediction = knn.predict(new_penguin_scaled)

print("\n--- New Prediction ---")
print(f"Predicted penguin species: {prediction[0]}")


--- Model Evaluation (k=5) ---
Accuracy: 0.9900

Classification Report:
              precision    recall  f1-score   support

      Adelie       0.98      1.00      0.99        48
   Chinstrap       1.00      0.94      0.97        18
      Gentoo       1.00      1.00      1.00        34

    accuracy                           0.99       100
   macro avg       0.99      0.98      0.99       100
weighted avg       0.99      0.99      0.99       100


Confusion Matrix:
[[48  0  0]
 [ 1 17  0]
 [ 0  0 34]]

--- New Prediction ---
Predicted penguin species: Adelie
